# Generated by Django 4.2.1 on 2023-05-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='languages',
        ),
    ]
