# Generated by Django 4.2.1 on 2023-05-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_name_country_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='languages',
            new_name='name',
        ),
    ]
